import {Movie} from './movie.model';

export const MOCKMOVIES: any[] = [
  {
    id: '1',
    title: 'Top Gun: Maverick',
    rating: 'PG-13',
    imgurl: 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fi0.wp.com%2Fwww.socialnews.xyz%2Fwp-content%2Fuploads%2F2019%2F12%2F15%2Ftop-gun-maverick-movie-latest-HD-Poster--scaled.jpg%3Fquality%3D90%26zoom%3D1%26ssl%3D1&f=1&nofb=1',
    score: '4.5',
    review: 'Tom Cruise delivers a better than average sequel that is a lot of fun, and I found myself enjoying this one more than the first one.'
  },
  {
    id: '2',
    title: 'Despicable Me',
    rating: 'PG',
    imgurl: 'https://resizing.flixster.com/uA07pd_5W7ciZbBiDF0GzQDq1EU=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2Y0NzM2Y2YxLTc5NmItNDA2OS04YjIzLTBhNDUxOTQ3NGU4Yi53ZWJw',
    score: '3.5',
    review: 'Borrowing heavily (and intelligently) from Pixar and Looney Tunes, Despicable Me is a surprisingly thoughtful, family-friendly treat with a few surprises of its own.'
  },
  {
    id: '3',
    title: 'Shrek',
    rating: 'PG',
    imgurl: 'https://picfiles.alphacoders.com/349/349440.jpg',
    score: '4',
    review: "While simultaneously embracing and subverting fairy tales, the irreverent Shrek also manages to tweak Disney's nose, provide a moral message to children, and offer viewers a funny, fast-paced ride."
  },
  {
    id: '4',
    title: 'Star Wars: Episode III -- Revenge of the Sith',
    rating: 'PG-13',
    imgurl: 'https://image.tmdb.org/t/p/original/9IhnxfbRH2kybbWrb4Ac8yvN2jP.jpg',
    score: '4.5',
    review: "With Episode III: Revenge of the Sith, George Lucas brings his second Star Wars trilogy to a suitably thrilling and often poignant -- if still a bit uneven -- conclusion."
  },
  {
    id: '5',
    title: "Schindler's List",
    rating: 'R',
    imgurl: 'https://www.gameindustry.com/wp-content/uploads/2018/09/schindlers_list.jpg',
    score: '5',
    review: "Schindler's List blends the abject horror of the Holocaust with Steven Spielberg's signature tender humanism to create the director's dramatic masterpiece"
  },
  {
    id: '6',
    title: "Raiders of the Lost Ark",
    rating: 'PG',
    imgurl: 'http://images.wikia.com/filmguide/images/1/11/Raiders_of_the_lost_ark_movie_poster.jpg',
    score: '4',
    review: "Featuring bravura set pieces, sly humor, and white-knuckle action, Raiders of the Lost Ark is one of the most consummately entertaining adventure pictures of all time."
  },
  {
    id: '7',
    title: "Twilight",
    rating: 'PG-13',
    imgurl: 'https://mypostercollection.com/wp-content/uploads/2019/08/Twilight-poster-e1566241293422.jpg',
    score: '2',
    review: "Having lost much of its bite transitioning to the big screen, Twilight will please its devoted fans, but do little for the uninitiated"
  },
  {
    id: '8',
    title: "1917",
    rating: 'R',
    imgurl: 'https://image.tmdb.org/t/p/original/3F2zrcg3Ab3MYKOICBDU9lpbHIK.jpg',
    score: '3.5',
    review: "Hard-hitting, immersive, and an impressive technical achievement, 1917 captures the trench warfare of World War I with raw, startling immediacy."
  },
  {
    id: '9',
    title: "National Treasure",
    rating: 'PG',
    imgurl: 'https://is2-ssl.mzstatic.com/image/thumb/Video/v4/24/63/73/24637338-d82a-6bf3-126f-8c6ac6cd0d0c/source/1600x2400sr.jpg',
    score: '2',
    review: "National Treasure is no treasure, but it's a fun ride for those who can forgive its highly improbable plot."
  },
  {
    id: '10',
    title: "Spider-Man 2",
    rating: 'PG-13',
    imgurl: 'https://hellhorror.com/images/inTheaters/origs/Spider-Man-2-2004-poster.jpg',
    score: '4.5',
    review: "Boasting an entertaining villain and deeper emotional focus, this is a nimble sequel that improves upon the original. "
  }
];
